[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta"

[project]
version = "0.0.5"
name = "phomemo_p12_tools"
description='Phomemo P12 printing tools'

readme = "README.md"

license = "MIT"

authors = [
    {name = 'TOKITA Hiroshi', email='tokita.hiroshi@gmail.com'},
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: System :: Hardware :: Hardware Drivers"
]

dependencies = [
    "Pillow>=9.2.0",
    "pycairo>=1.23.0",
    "pyserial>=3.5",
]

[project.urls]
homepage='https://github.com/soburi/phomemo-p12'
repository='https://github.com/soburi/phomemo-p12'

[project.scripts]
phomemo_render_label = "phomemo_p12_tools.render_label:main"
phomemo_print_p12 = "phomemo_p12_tools.print_p12:main"
